import { registerSW } from 'virtual:pwa-register'
import { parsePdf } from './parser'
import { storage } from './db'
import { humanMonth, normalizeCrossMonth, timeLabel } from './schedule'
import type { Candidate, MonthRecord, ParsedSchedule, Shift } from './types'
import './style.css'

const app = document.querySelector<HTMLDivElement>('#app')!
let months: MonthRecord[]=[]; let selected=''; let selectedShift: Shift|null=null; let section:'calendar'|'documents'='calendar'; let pending: {file:File; parsed:ParsedSchedule}|null=null
let applyUpdate: ((reloadPage?: boolean) => Promise<void>) | undefined
const esc=(s:string)=>s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]!))
const today=new Date().toISOString().slice(0,10)
async function refresh(){months=await storage.months();selected=selected&&months.some(m=>m.id===selected)?selected:(months[0]?.id||'');render()}
function shifts(){return normalizeCrossMonth(months.flatMap(x=>x.shifts))}
function nextShift(){return shifts().find(x=>x.date>=today)}
function render(){ const active=months.find(x=>x.id===selected); const next=nextShift(); app.innerHTML=`<main>
 <header><div class="brand"><span>▣</span><div><h1>${section==='calendar'?'Мои смены':'Графики'}</h1><small>${section==='calendar'?'Только на этом устройстве':'Источники данных календаря'}</small></div></div><button class="icon" id="settings" aria-label="Настройки">⚙</button></header>
 ${section==='documents'?documentsView():!months.length?welcome():`<section class="hero"><p>Ближайшая смена</p>${next?`<h2>${date(next.date)}</h2><strong>${next.hours} ч</strong><span>${timeLabel(next)} · ${esc(next.code)}</span>`:'<h2>График не загружен</h2><span>Добавьте следующий месячный PDF</span>'}</section>${monthView(active!)}`}
 </main><nav class="tabs" aria-label="Разделы"><button data-section="calendar" class="${section==='calendar'?'active':''}">▣<span>Календарь</span></button><button data-section="documents" class="${section==='documents'?'active':''}">▤<span>Графики</span></button></nav><input id="file" type="file" accept="application/pdf,.pdf" hidden><dialog id="dialog"></dialog>`; bind() }
function welcome(){return `<section class="welcome"><div class="shield">⌂</div><h2>Ваш график остаётся вашим</h2><p>PDF обрабатывается прямо в браузере и сохраняется только на этом устройстве. Мы не отправляем файл, смены или Delta-номер на сервер.</p><button class="primary" id="import">Выбрать PDF-график</button><small>Поддерживаются месячные PDF Delta. Интернет для импорта не нужен после установки.</small></section>`}
function monthView(m:MonthRecord){const d=new Date(`${m.id}-01T12:00:00`);const first=(d.getDay()+6)%7;const days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();const byDay=new Map(m.shifts.map(s=>[Number(s.date.slice(8)),s]));const leave=new Set((m.leaveDates||[]).map(x=>Number(x.slice(8))));const cells=Array.from({length:first},()=>'<i></i>').concat(Array.from({length:days},(_,i)=>{const s=byDay.get(i+1), onLeave=leave.has(i+1);return `<button class="day ${s?'work':''} ${onLeave?'leave':''} ${selectedShift?.date===s?.date?'selected':''} ${s?.date===today?'today':''}" ${s?`data-shift="${i+1}"`:''}><b>${i+1}</b>${s?`<small>${esc(s.code)}</small>`:onLeave?'<small>P</small>':''}</button>`})).join('');const details=selectedShift?`<section class="shift-details" id="shift-details"><div class="detail-icon">◷</div><div><b>${date(selectedShift.date)}</b><span>${selectedShift.hours} ч · ${timeLabel(selectedShift)} · код ${esc(selectedShift.code)}</span></div></section>`:'';return `<nav class="months"><button id="prev" ${!adjacent(-1)?'disabled':''}>‹</button><button id="picker">${humanMonth(m.id)}</button><button id="next" ${!adjacent(1)?'disabled':''}>›</button></nav><section class="calendar" id="calendar"><div class="week">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<span>${x}</span>`).join('')}</div><div class="grid">${cells}</div><div class="legend"><span><i class="dot long"></i>24 часа</span><span><i class="dot regular"></i>обычная смена</span><span><i class="dot vacation"></i>P · отпуск</span></div></section>${details}<button class="add" id="import">＋ <span>Импортировать PDF</span></button>`}
function documentsView(){return `<section class="documents-intro"><p>Оригинальные PDF и графики хранятся только на этом устройстве. Нажмите график, чтобы открыть его.</p><button class="primary" id="import">Импортировать PDF</button></section><h2 class="list-title">Загруженные графики</h2><section class="documents">${months.length?months.map(m=>`<article data-open-pdf="${m.id}"><div class="doc-icon">▤</div><div><b>${humanMonth(m.id)}</b><span>${esc(m.fileName)}</span><small>${m.shifts.length} смен · загружен ${new Date(m.importedAt).toLocaleDateString('ru-RU')}</small></div><button class="delete-month" data-delete-month="${m.id}" aria-label="Удалить ${m.id}">⌫</button></article>`).join(''):'<p>Графики ещё не импортированы.</p>'}</section><p class="documents-hint">Повторный импорт заменяет только соответствующий месяц и не создаёт дублей.</p>`}
function date(v:string){return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',weekday:'short'}).format(new Date(`${v}T12:00:00`))}
function adjacent(n:number){const i=months.findIndex(x=>x.id===selected);return months[i+n]}
function bind(){document.querySelector('#import')?.addEventListener('click',()=>document.querySelector<HTMLInputElement>('#file')!.click());document.querySelector('#file')?.addEventListener('change',onFile);document.querySelector('#prev')?.addEventListener('click',()=>moveMonth(-1));document.querySelector('#next')?.addEventListener('click',()=>moveMonth(1));document.querySelector('#picker')?.addEventListener('click',showMonths);document.querySelector('#settings')?.addEventListener('click',showSettings);document.querySelectorAll<HTMLButtonElement>('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section as 'calendar'|'documents';selectedShift=null;render()});document.querySelectorAll<HTMLButtonElement>('[data-shift]').forEach(b=>b.onclick=()=>{const m=months.find(x=>x.id===selected)!;const s=m.shifts.find(x=>Number(x.date.slice(8))===Number(b.dataset.shift));selectedShift=selectedShift?.date===s?.date?null:s||null;render();if(selectedShift)setTimeout(()=>document.querySelector('#shift-details')?.scrollIntoView({behavior:'smooth',block:'nearest'}),20)});document.querySelectorAll<HTMLElement>('[data-open-pdf]').forEach(x=>x.onclick=()=>openPdf(x.dataset.openPdf!));document.querySelectorAll<HTMLButtonElement>('[data-delete-month]').forEach(b=>b.onclick=async e=>{e.stopPropagation();const id=b.dataset.deleteMonth!;if(confirm(`Удалить ${humanMonth(id)} вместе со всеми сменами и PDF?`)){await storage.remove(id);if(selected===id)selected='';await refresh()}});let start=0;const calendar=document.querySelector<HTMLElement>('#calendar');calendar?.addEventListener('pointerdown',e=>{start=e.clientX});calendar?.addEventListener('pointerup',e=>{const delta=e.clientX-start;if(Math.abs(delta)>55)moveMonth(delta<0?1:-1)})}
async function openPdf(id:string){const pdf=await storage.pdf(id);if(!pdf){open(`<h2>Оригинал недоступен</h2><p>Этот месяц был импортирован до обновления приложения, когда PDF ещё не сохранялся. Импортируйте исходный файл повторно.</p><button id="close">Понятно</button>`);document.querySelector('#close')!.addEventListener('click',close);return}const url=URL.createObjectURL(pdf);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)}
function moveMonth(direction:number){const target=adjacent(direction);if(target){selected=target.id;selectedShift=null;render()}}
async function onFile(e:Event){const file=(e.target as HTMLInputElement).files?.[0];if(!file)return; try{open(`<div class="busy"><div class="spinner"></div><h2>Анализируем PDF</h2><p>Файл не покидает ваше устройство.</p></div>`);const parsed=await parsePdf(file);pending={file,parsed};chooseDelta(parsed)}catch(error){open(`<h2>Не удалось прочитать график</h2><p>${esc(error instanceof Error?error.message:'Неизвестная ошибка')}</p><button class="primary" autofocus>Закрыть</button>`);(document.querySelector('dialog button') as HTMLButtonElement).onclick=close}finally{(e.target as HTMLInputElement).value=''}}
function chooseDelta(p:ParsedSchedule){const preferred=months[0]?.deltaNumber;open(`<h2>Чей это график?</h2><p>${humanMonth(p.month)} · найдены номера из PDF. ${p.warnings.join(' ')}</p><div class="choices">${p.candidates.map(c=>`<button data-delta="${c.number}" class="choice ${c.number===preferred?'recommended':''}"><b>${c.number}</b><span>${c.shifts.length} смен${c.number===preferred?' · использовали раньше':''}</span></button>`).join('')}</div><button id="cancel">Отмена</button>`);document.querySelectorAll<HTMLButtonElement>('[data-delta]').forEach(b=>b.onclick=()=>savePick(p.candidates.find(x=>x.number===b.dataset.delta)!));document.querySelector('#cancel')!.addEventListener('click',close)}
async function savePick(c:Candidate){if(!pending)return;const old=months.find(m=>m.id===pending!.parsed.month);const hash=await digest(pending.file);const record:MonthRecord={id:pending.parsed.month,fileName:pending.file.name,importedAt:Date.now(),hash,shifts:c.shifts,leaveDates:c.leaveDates,deltaNumber:c.number,status:old&&old.hash!==hash?'changed':'local',calendar:{dirty:true}};await Promise.all([storage.put(record),storage.putPdf(record.id,pending.file)]);await storage.set('deltaNumber',c.number);close();pending=null;selected=record.id;await refresh();if(!old)calendarOffer()}
async function digest(file:File){const a=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return [...new Uint8Array(a)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function showMonths(){open(`<h2>Загруженные месяцы</h2><div class="choices">${months.map(m=>`<button class="choice" data-month="${m.id}"><b>${humanMonth(m.id)}</b><span>${esc(m.fileName)} · ${m.shifts.length} смен</span></button>`).join('')}</div><button id="close">Закрыть</button>`);document.querySelectorAll('[data-month]').forEach(b=>b.addEventListener('click',()=>{selected=(b as HTMLElement).dataset.month!;close();render()}));document.querySelector('#close')!.addEventListener('click',close)}
function calendarOffer(){setTimeout(()=>open(`<h2>Синхронизировать с Google Calendar?</h2><p>В будущем вы сможете по явному действию создать отдельный календарь смен. Сейчас интеграция ожидает настройки безопасного OAuth Client ID — приложение полностью работает и без неё.</p><button class="primary" id="ok">Понятно</button>`),60);setTimeout(()=>document.querySelector('#ok')?.addEventListener('click',close),70)}
function showSettings(){open(`<h2>Настройки</h2><p>Данные хранятся в IndexedDB браузера. Удаление нельзя отменить.</p><button class="calendar-button" id="google">Google Calendar <span>Скоро</span></button><button class="danger" id="wipe">Удалить все локальные данные</button><button id="close">Закрыть</button>`);document.querySelector('#close')!.addEventListener('click',close);document.querySelector('#google')!.addEventListener('click',()=>{open(`<h2>Google Calendar</h2><p>Синхронизация будет создавать отдельный календарь смен и запрашивать доступ только по вашему действию. Для включения нужен production OAuth Client ID; сейчас ни аккаунт, ни данные не передаются.</p><button class="primary" id="close">Понятно</button>`);document.querySelector('#close')!.addEventListener('click',close)});document.querySelector('#wipe')!.addEventListener('click',async()=>{if(confirm('Удалить все PDF-метаданные, смены и настройки с этого устройства?')){await storage.clear();close();await refresh()}})}
function open(html:string){const d=document.querySelector<HTMLDialogElement>('#dialog')!;d.innerHTML=html;d.showModal()}function close(){document.querySelector<HTMLDialogElement>('#dialog')?.close()}
function offerUpdate() {
  if (document.querySelector('#update-notice')) return
  const notice = document.createElement('aside')
  notice.id = 'update-notice'; notice.setAttribute('role', 'status')
  notice.innerHTML = `<div><b>Доступна новая версия</b><span>Ваши сохранённые графики останутся на устройстве.</span></div><button class="primary">Перезапустить</button>`
  notice.querySelector('button')!.addEventListener('click', async () => {
    const button = notice.querySelector('button') as HTMLButtonElement
    button.disabled = true; button.textContent = 'Обновляем…'
    // Sends SKIP_WAITING and reloads only after the new worker controls this page.
    await applyUpdate?.(true)
  })
  document.body.append(notice)
}
applyUpdate = registerSW({ onNeedRefresh: offerUpdate })
refresh()
